version: 2.1
orbs:
  circleci-cli: circleci/circleci-cli@0.1.9
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.49.0-jammy
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
     - run:
      #...
      # run tests and store XML files to a subdirectory, for example, test-results
      #...
      - store_test_results:
        path: test-results
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run IDS Sanity Test
          command: yarn plytests
